=== CCC-8/IP-Assignment/public/xml/users.dtd
<?xml version="1.0" encoding="UTF-8"?>


  <!ELEMENT users (user+)>
  <!ELEMENT user (userID, username, email, phoneno, address, avatar, created_at, updated_at)>
  <!ELEMENT userID (#PCDATA)>
  <!ELEMENT username (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT phoneno (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ELEMENT avatar (#PCDATA)>
  <!ELEMENT created_at (#PCDATA)>
  <!ELEMENT updated_at (#PCDATA)>

=== CCC-8/IP-Assignment/public/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE users SYSTEM "users.dtd">-->


<users 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation='users.xsd'>
    
    <user>
        <userID>1</userID>
        <username>customer1</username>
        <email>tangch-wm20@student.tarc.edu.my</email>
        <phoneno>019-3846891</phoneno>
        <address>No 12 JLN SP 6/1 Bandar blablabla 47100 Selangor</address>
        <avatar>EBybv6AIQDElOV3V0bagBzffViehSUyyQScCWphY.jpg</avatar>
        <created_at>2023-04-29T18:51:19</created_at>
        <updated_at>2023-04-29T19:30:45</updated_at>
    </user>
    <user>
        <userID>2</userID>
        <username>customer2</username>
        <email>ahhhaohao@gmail.com</email>
        <phoneno>019-3236991</phoneno>
        <address>No 12 JLN SP 6/1 Bandar blablabla 47100 Selangor</address>
        <avatar>UtAUiNPmqBfmrPpqM85ok6nl4iL1LJCx369m3AVj.jpg</avatar>
        <created_at>2023-04-29T18:51:36</created_at>
        <updated_at>2023-04-29T19:36:18</updated_at>
    </user>
    <user>
        <userID>3</userID>
        <username>customer3</username>
        <email>xiiaohao0701@gmail.com</email>
        <phoneno>012-3456789</phoneno>
        <address/>
        <avatar/>
        <created_at>2023-04-29T18:52:02</created_at>
        <updated_at>2023-04-29T18:52:35</updated_at>
    </user>
</users>
